### PR TITLE
Update api to v2 endpoints

### PR DESCRIPTION
**Pull request by Tetracyl**

### CODE REVIEW

**Comment by TBNRItzDoge** [comment]
this is a great pr thanks for the effort i see it must've taken ages @dicedtomatoreal mergeeee

**Comment by Tetracyl** [comment]
Took me hours upon hours to make this pr

**Comment by apex2504** [comment]
/v2/yesterday is not a valid endpoint. getting data for the previous day now uses ?yesterday=true - similar to how sorting and strict work.

**Comment by puf17640** [comment]
@EliteDaMyth this doesnt even work man

**Pull request merged**
